name: Package on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Get version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Package Extension
        run: npm run package

      - name: Create and push tag
        run: |
          git config --local user.email "albertobarrago@gmail.com"
          git config --local user.name "alBz"
          git tag -a v${{ steps.package-version.outputs.version }} -m "Release v${{ steps.package-version.outputs.version }}"
          git push origin v${{ steps.package-version.outputs.version }}

      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-oracle-v${{ steps.package-version.outputs.version }}
          path: '*.vsix'
          retention-days: 90